## Built-in, reviewed URL aliases for common web applications.
##
## A prepack is only a stable name for an entry URL. Identity, window,
## profile, package metadata and navigation behavior are generated by the same
## URL-only path used for arbitrary sites; no site-specific allow-list is
## required to make an authenticated app work.

import std/strutils

import ./[generator, manifest]

type
  PackPrepack* = object
    slug*: string
    url*: string

proc reviewedPrepacks*(): seq[PackPrepack] =
  @[
    PackPrepack(slug: "youtube", url: "https://www.youtube.com/"),
    PackPrepack(slug: "gmail", url: "https://mail.google.com/mail/u/0/"),
    PackPrepack(slug: "google-analytics",
      url: "https://analytics.google.com/analytics/web/")
  ]

proc loadPrepack*(slug: string): PackResult[PackManifest] =
  let normalized = slug.strip().toLowerAscii()
  for prepack in reviewedPrepacks():
    if prepack.slug == normalized:
      return generateManifest(prepack.url)
  failure[PackManifest](invalidManifest, "unknown prepack: " & slug)
