# Built-in prepack: `nimino pack prepack youtube`
name = "YouTube"
id = "com.nimino.youtube"
url = "https://www.youtube.com/"
profile = "default"

[window]
width = 1280
height = 800
resizable = true

[package]
version = "0.1.0"
description = "YouTube web application"
publisher = "Nimino"
homepage = "https://www.youtube.com/"
categories = ["AudioVideo"]

[navigation]
allow = ["https://www.youtube.com/**", "https://youtube.com/**", "https://*.youtube.com/**", "https://accounts.google.com/**", "https://*.googleusercontent.com/**"]
external = ["https://support.google.com/**"]
