import std/[json, os]

import nimino_pack

proc usage() =
  stderr.writeLine("usage: nimino pack <manifest.toml> [--out <directory>]")
  quit(2)

proc manifestJson(manifest: PackManifest): JsonNode =
  %*{
    "name": manifest.name,
    "id": manifest.id,
    "url": manifest.url,
    "profile": manifest.profile,
    "window": {
      "width": manifest.window.width,
      "height": manifest.window.height,
      "resizable": manifest.window.resizable
    },
    "navigation": {
      "allow": manifest.navigationAllow,
      "external": manifest.navigationExternal
    },
    "permissions": {"allow": manifest.permissionsAllow},
    "injection": {
      "css": manifest.css,
      "javascript": manifest.javascript
    }
  }

if paramCount() < 2 or paramStr(1) != "pack":
  usage()
let loaded = loadManifest(paramStr(2))
if not loaded.isOk:
  stderr.writeLine("nimino pack: " & loaded.error.detail)
  quit(1)
let output = manifestJson(loaded.value).pretty()
if paramCount() == 2:
  echo output
elif paramCount() == 4 and paramStr(3) == "--out":
  let directory = paramStr(4)
  if directory.len == 0:
    usage()
  createDir(directory)
  let manifestPath = directory / "nimino-manifest.json"
  writeFile(manifestPath, output & "\n")
  let launcherPath = directory / "run-nimino.sh"
  writeFile(launcherPath, "#!/bin/sh\n# Generated by nimino-pack.\nexec nimino-host --manifest \"$(dirname \"$0\")/nimino-manifest.json\"\n")
  setFilePermissions(launcherPath, {fpUserExec, fpUserRead, fpUserWrite,
    fpGroupExec, fpGroupRead, fpOthersExec, fpOthersRead})
  let windowsLauncherPath = directory / "run-nimino.cmd"
  writeFile(windowsLauncherPath, "@echo off\r\nrem Generated by nimino-pack.\r\nnimino-host.exe --manifest \"%~dp0nimino-manifest.json\"\r\n")
  echo manifestPath
else:
  usage()
