import std/[json, os, strutils]

import nimino_pack

proc usage() =
  stderr.writeLine("usage: nimino pack <manifest.toml> [--out <directory>] [--host <executable>]")
  quit(2)

proc manifestJson(manifest: PackManifest): JsonNode =
  %*{
    "name": manifest.name,
    "id": manifest.id,
    "url": manifest.url,
    "profile": manifest.profile,
    "window": {
      "width": manifest.window.width,
      "height": manifest.window.height,
      "resizable": manifest.window.resizable
    },
    "navigation": {
      "allow": manifest.navigationAllow,
      "external": manifest.navigationExternal
    },
    "permissions": {"allow": manifest.permissionsAllow},
    "injection": {
      "css": manifest.css,
      "javascript": manifest.javascript
    }
  }

if paramCount() < 2 or paramStr(1) != "pack":
  usage()
let loaded = loadManifest(paramStr(2))
if not loaded.isOk:
  stderr.writeLine("nimino pack: " & loaded.error.detail)
  quit(1)
let output = manifestJson(loaded.value).pretty()
if paramCount() == 2:
  echo output
elif paramCount() in {4, 6} and paramStr(3) == "--out":
  let directory = paramStr(4)
  if directory.len == 0:
    usage()
  createDir(directory)
  let manifestPath = directory / "nimino-manifest.json"
  writeFile(manifestPath, output & "\n")
  let launcherPath = directory / "run-nimino.sh"
  let hostName = if paramCount() == 6 and paramStr(5) == "--host":
                   extractFilename(paramStr(6))
                 else: "nimino-host"
  if paramCount() == 6:
    if paramStr(5) != "--host" or not fileExists(paramStr(6)):
      usage()
    copyFile(paramStr(6), directory / hostName)
  writeFile(launcherPath, "#!/bin/sh\n# Generated by nimino-pack.\nexec \"$(dirname \"$0\")/" & hostName & "\" --manifest \"$(dirname \"$0\")/nimino-manifest.json\"\n")
  setFilePermissions(launcherPath, {fpUserExec, fpUserRead, fpUserWrite,
    fpGroupExec, fpGroupRead, fpOthersExec, fpOthersRead})
  let windowsLauncherPath = directory / "run-nimino.cmd"
  let windowsHostName = if hostName.endsWith(".exe"): hostName else: hostName & ".exe"
  writeFile(windowsLauncherPath, "@echo off\r\nrem Generated by nimino-pack.\r\n\"%~dp0" & windowsHostName & "\" --manifest \"%~dp0nimino-manifest.json\"\r\n")
  let desktopPath = directory / "nimino.desktop"
  writeFile(desktopPath, "[Desktop Entry]\nType=Application\nName=" & loaded.value.name &
    "\nExec=" & directory / "run-nimino.sh" & "\nTerminal=false\nCategories=Utility;\n")
  let installScriptPath = directory / "install-windows.ps1"
  writeFile(installScriptPath, "# Generated by nimino-pack.\n$target = Join-Path $env:LOCALAPPDATA 'Nimino\\" & loaded.value.id & "'\nNew-Item -ItemType Directory -Force -Path $target | Out-Null\nCopy-Item -Recurse -Force (Join-Path $PSScriptRoot '*') $target\nWrite-Host \"Installed Nimino app at $target\"\n")
  echo manifestPath
else:
  usage()
