import std/[json, os, strutils]

import nimino_pack

proc usage() =
  stderr.writeLine("usage: nimino pack <manifest.toml> [--out <directory>] [--host <executable>]")
  stderr.writeLine("       nimino pack <url> --name <name> --id <id> [--out <directory>] [--host <executable>]")
  quit(2)

proc manifestJson(manifest: PackManifest): JsonNode =
  %*{
    "name": manifest.name,
    "id": manifest.id,
    "url": manifest.url,
    "icon": manifest.icon,
    "profile": manifest.profile,
    "window": {
      "width": manifest.window.width,
      "height": manifest.window.height,
      "resizable": manifest.window.resizable
    },
    "navigation": {
      "allow": manifest.navigationAllow,
      "external": manifest.navigationExternal
    },
    "permissions": {"allow": manifest.permissionsAllow},
    "injection": {
      "css": manifest.css,
      "javascript": manifest.javascript
    }
  }

proc desktopEscape(value: string): string =
  ## Exec entries use desktop-entry escaping rather than shell quoting.
  for character in value:
    case character
    of '\\', ' ', '\t':
      result.add('\\')
      result.add(character)
    of '\n', '\r':
      result.add(' ')
    else:
      result.add(character)

if paramCount() < 2 or paramStr(1) != "pack":
  usage()
var loaded: PackResult[PackManifest]
let source = paramStr(2)
if source.startsWith("http://") or source.startsWith("https://"):
  var name = ""
  var id = ""
  var profile = "default"
  var icon = ""
  var index = 3
  while index <= paramCount():
    if index == paramCount():
      usage()
    let flag = paramStr(index)
    let value = paramStr(index + 1)
    case flag
    of "--name": name = value
    of "--id": id = value
    of "--profile": profile = value
    of "--icon": icon = value
    of "--out", "--host": index += 1
    else: usage()
    index += 2
  if name.len == 0 or id.len == 0:
    usage()
  loaded = validate(PackManifest(
    name: name,
    id: id,
    url: source,
    icon: icon,
    profile: profile,
    window: PackWindowOptions(width: 1200, height: 800, resizable: true)))
else:
  loaded = loadManifest(source)
if not loaded.isOk:
  stderr.writeLine("nimino pack: " & loaded.error.detail)
  quit(1)
var output = manifestJson(loaded.value).pretty()
var outputDirectory = ""
var hostPath = ""
var index = 3
while index <= paramCount():
  if index == paramCount(): usage()
  case paramStr(index)
  of "--out": outputDirectory = paramStr(index + 1)
  of "--host": hostPath = paramStr(index + 1)
  of "--name", "--id", "--profile", "--icon":
    if not (source.startsWith("http://") or source.startsWith("https://")): usage()
  else: usage()
  index += 2
if outputDirectory.len == 0:
  echo output
else:
  let directory = outputDirectory
  if directory.len == 0:
    usage()
  createDir(directory)
  var packaged = loaded.value
  proc packageFiles(paths: var seq[string]) =
    for index in 0 ..< paths.len:
      if not fileExists(paths[index]):
        continue
      let fileName = extractFilename(paths[index])
      if fileName.len == 0 or fileName in [".", ".."]:
        stderr.writeLine("nimino pack: injected file path has no usable filename")
        quit(1)
      copyFile(paths[index], directory / fileName)
      paths[index] = fileName
  if packaged.icon.len > 0 and fileExists(packaged.icon):
    let iconName = extractFilename(packaged.icon)
    if iconName.len == 0 or iconName in [".", ".."]:
      stderr.writeLine("nimino pack: icon path has no usable filename")
      quit(1)
    copyFile(packaged.icon, directory / iconName)
    packaged.icon = iconName
  packageFiles(packaged.css)
  packageFiles(packaged.javascript)
  output = manifestJson(packaged).pretty()
  let manifestPath = directory / "nimino-manifest.json"
  writeFile(manifestPath, output & "\n")
  let launcherPath = directory / "run-nimino.sh"
  let hostName = if hostPath.len > 0:
                   extractFilename(hostPath)
                 else: "nimino-host"
  if hostPath.len > 0:
    if not fileExists(hostPath):
      usage()
    copyFile(hostPath, directory / hostName)
  writeFile(launcherPath, "#!/bin/sh\n# Generated by nimino-pack.\nexec \"$(dirname \"$0\")/" & hostName & "\" --manifest \"$(dirname \"$0\")/nimino-manifest.json\"\n")
  setFilePermissions(launcherPath, {fpUserExec, fpUserRead, fpUserWrite,
    fpGroupExec, fpGroupRead, fpOthersExec, fpOthersRead})
  let windowsLauncherPath = directory / "run-nimino.cmd"
  let windowsHostName = if hostName.endsWith(".exe"): hostName else: hostName & ".exe"
  writeFile(windowsLauncherPath, "@echo off\r\nrem Generated by nimino-pack.\r\n\"%~dp0" & windowsHostName & "\" --manifest \"%~dp0nimino-manifest.json\"\r\n")
  let desktopPath = directory / "nimino.desktop"
  writeFile(desktopPath, "[Desktop Entry]\nType=Application\nName=" & loaded.value.name &
    "\nExec=" & desktopEscape(directory / "run-nimino.sh") &
    "\nTerminal=false\nCategories=Utility;\n")
  let installScriptPath = directory / "install-windows.ps1"
  writeFile(installScriptPath, "# Generated by nimino-pack.\n$target = Join-Path $env:LOCALAPPDATA 'Nimino\\" & loaded.value.id & "'\nNew-Item -ItemType Directory -Force -Path $target | Out-Null\nCopy-Item -Recurse -Force (Join-Path $PSScriptRoot '*') $target\nWrite-Host \"Installed Nimino app at $target\"\n")
  echo manifestPath
