#!/usr/bin/env bash
set -euo pipefail

# Stage the two independently distributable Nimino components beside the
# ready-made site installers.
#
#   nimino-core  the nimino-host runtime that every packaged application
#                embeds. End users receive it inside an installer; this
#                archive is for embedders who build their own bundles.
#   nimino-pack  the packaging toolkit CLI. It is a build-time developer
#                tool and imports no other Nimino package, so it needs no
#                GUI SDK at all.
#
# The two are released together from this monorepo but carry no build-time
# dependency on each other: pack only ever receives a host binary by path
# (`--host`), never by linkage.

cli=${1:?usage: build_component_release.sh <nimino-cli> <linux-host> <windows-host> <output-dir> <version>}
linux_host=${2:?usage: build_component_release.sh <nimino-cli> <linux-host> <windows-host> <output-dir> <version>}
windows_host=${3:?usage: build_component_release.sh <nimino-cli> <linux-host> <windows-host> <output-dir> <version>}
output=${4:?usage: build_component_release.sh <nimino-cli> <linux-host> <windows-host> <output-dir> <version>}
version=${5:?usage: build_component_release.sh <nimino-cli> <linux-host> <windows-host> <output-dir> <version>}

test -x "$cli" || { echo "component release: CLI is not executable: $cli" >&2; exit 1; }
test -x "$linux_host" || { echo "component release: Linux host is not executable: $linux_host" >&2; exit 1; }
test -s "$windows_host" || { echo "component release: Windows host is missing: $windows_host" >&2; exit 1; }

assets="$output/assets"
test -d "$assets" || {
  echo "component release: assets directory is missing: $assets" >&2
  echo "component release: run build_site_release.sh first" >&2
  exit 1
}

repo_root=$(cd "$(dirname "$0")/../.." && pwd)
license="$repo_root/LICENSE"
pack_schema="$repo_root/packages/pack/schema/nimino-pack.schema.json"
test -s "$license" || { echo "component release: LICENSE is missing: $license" >&2; exit 1; }
test -s "$pack_schema" || { echo "component release: pack schema is missing: $pack_schema" >&2; exit 1; }

webview2_loader=${NIMINO_WEBVIEW2_LOADER:-/opt/nimino/webview2/x64/WebView2Loader.dll}
test -s "$webview2_loader" || {
  echo "component release: WebView2Loader.dll is missing: $webview2_loader" >&2
  exit 1
}
pcre_dll=${NIMINO_WINDOWS_PCRE_DLL:-/opt/nimino/windows-dlls/pcre64.dll}
test -s "$pcre_dll" || { echo "component release: pcre64.dll is missing: $pcre_dll" >&2; exit 1; }

staging=$(mktemp -d)
trap 'rm -rf "$staging"' EXIT

# Archive members are owned by root:root with a fixed mtime so a rebuild of
# the same tag produces byte-identical archives and a stable SHA256SUMS.
# Everything is packed under a single top-level directory named after the
# archive, so extracting never scatters files into the current directory.
tar_reproducible() {
  local archive=$1
  local directory=$2
  tar --sort=name --owner=0 --group=0 --numeric-owner \
    --mtime="@${SOURCE_DATE_EPOCH:-0}" \
    -czf "$archive" -C "$(dirname "$directory")" "$(basename "$directory")"
}

## nimino-core, Linux x86_64 -------------------------------------------------
core_linux="$staging/nimino-core-$version-linux-x86_64"
mkdir -p "$core_linux"
cp "$linux_host" "$core_linux/nimino-host"
chmod 0755 "$core_linux/nimino-host"
cp "$license" "$core_linux/LICENSE"
cat > "$core_linux/README.txt" <<EOF
nimino-core $version -- Linux x86_64

nimino-host is the generic Nimino runtime. Point it at a bundle manifest
generated by nimino-pack:

  ./nimino-host --manifest /path/to/nimino-manifest.json

Runtime requirements (resolved by the package manager when you install a
generated .deb/.rpm instead of this archive):

  GTK 4              Debian/Ubuntu libgtk-4-1     Fedora/RHEL gtk4
  WebKitGTK 6.0      Debian/Ubuntu libwebkitgtk-6.0-4
                     Fedora/RHEL webkitgtk6.0 (EL10 needs EPEL; EL9 is unsupported)

PCRE is linked statically, so no libpcre is required. This archive is the
runtime only: use the nimino-pack archive to generate bundles and installers.
EOF
tar_reproducible "$assets/nimino-core-$version-linux-x86_64.tar.gz" "$core_linux"

## nimino-core, Windows x64 --------------------------------------------------
core_windows="$staging/nimino-core-$version-windows-x64"
mkdir -p "$core_windows"
cp "$windows_host" "$core_windows/nimino-host.exe"
cp "$webview2_loader" "$core_windows/WebView2Loader.dll"
cp "$pcre_dll" "$core_windows/pcre64.dll"
cp "$license" "$core_windows/LICENSE"
cat > "$core_windows/README.txt" <<EOF
nimino-core $version -- Windows x64

nimino-host.exe is the generic Nimino runtime. Point it at a bundle manifest
generated by nimino-pack:

  nimino-host.exe --manifest C:\\path\\to\\nimino-manifest.json

WebView2Loader.dll and pcre64.dll must stay beside the executable. The
WebView2 Evergreen Runtime itself is a machine-wide Microsoft component: the
generated NSIS/MSI installers bootstrap it when missing, but this archive
does not. Install the Runtime first if the host fails to start.
EOF
# zip stores each member's mtime, so normalize them the same way the tar
# archives are normalized before packing.
find "$core_windows" -exec touch -h -d "@${SOURCE_DATE_EPOCH:-0}" {} +
(cd "$staging" && zip -q -X -r -o "$assets/nimino-core-$version-windows-x64.zip" \
  "$(basename "$core_windows")")

## nimino-pack, Linux x86_64 -------------------------------------------------
# The packaging toolkit is a developer tool. It is published for Linux only:
# every generator it drives (dpkg-deb, rpmbuild, appimagetool, makensis,
# wixl) is invoked from the Linux container toolchain, and shipping a
# Windows CLI that cannot reach them would fail at use time rather than at
# download time.
pack_linux="$staging/nimino-pack-$version-linux-x86_64"
mkdir -p "$pack_linux"
cp "$cli" "$pack_linux/nimino"
chmod 0755 "$pack_linux/nimino"
cp "$license" "$pack_linux/LICENSE"
cp "$pack_schema" "$pack_linux/nimino-pack.schema.json"
cat > "$pack_linux/README.txt" <<EOF
nimino-pack $version -- Linux x86_64

The Nimino packaging toolkit. Wrap a URL or manifest into a bundle, then
generate platform installers:

  ./nimino pack https://example.com --out build/example --host ./nimino-host
  ./nimino package-linux build/example --format deb --out build/packages \\
    --arch amd64 --maintainer 'You <you@example.invalid>'

The host executable passed to --host comes from the nimino-core archive; the
two components are versioned and released together but are otherwise
independent.

nimino-pack links no GUI SDK. It does require OpenSSL for HTTPS icon
discovery, and each package format needs its own generator on PATH:

  deb       dpkg-deb            rpm       rpmbuild
  appimage  appimagetool        nsis      makensis
  flatpak   flatpak-builder     msi       wixl

A missing generator fails the requested format instead of emitting an
incomplete artifact. nimino-pack.schema.json describes the manifest format.
EOF
tar_reproducible "$assets/nimino-pack-$version-linux-x86_64.tar.gz" "$pack_linux"

## Checksums and release notes ----------------------------------------------
# SHA256SUMS must cover the component archives too, so it is regenerated over
# the complete asset set. Removing it first keeps the stale entry out of the
# glob that rebuilds it.
rm -f "$assets/SHA256SUMS"
(cd "$assets" && sha256sum -- * > SHA256SUMS)

notes="$output/RELEASE-NOTES.txt"
test -s "$notes" || { echo "component release: release notes are missing: $notes" >&2; exit 1; }
printf '%s\n' \
  '' \
  'Components (released independently of the site installers):' \
  "  nimino-core-$version-linux-x86_64.tar.gz    nimino-host runtime" \
  "  nimino-core-$version-windows-x64.zip        nimino-host.exe runtime + WebView2Loader.dll, pcre64.dll" \
  "  nimino-pack-$version-linux-x86_64.tar.gz    nimino packaging CLI" \
  '' \
  'nimino-core is the runtime embedded in every packaged application.' \
  'nimino-pack is the build-time packaging toolkit and depends on no other' \
  'Nimino package; it receives a host binary by path, never by linkage.' \
  'nimino-pack is Linux-only: its package generators are Linux tools.' \
  >> "$notes"

echo "nimino component release staged: nimino-core and nimino-pack $version"
